name: Contract Tests

on:
  push:
    branches:
      - master
    pull_request:

env:
  PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
  PACT_BROKER_USERNAME: ${{ secrets.PACT_BROKER_USERNAME }}
  PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}

jobs:
  contract-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Start pact broker
        run: docker compose up -d --wait --wait-timeout 150

      - name: Install ngrok
        run: curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && \
          sudo apt update && sudo apt install ngrok

      - name: Start ngrok
        run: ngrok http 8000 &

      - name: Display ngrok URL
        run: curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      - name: Run Consumer contract tests
        working-directory: ./petstore-consumer
        run: mvn clean test

      - name: Publish Pact verification results
        if: success()
        env:
#          PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
#          PACT_BROKER_USERNAME: ${{ secrets.PACT_BROKER_USERNAME }}
#          PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}
          PACT_CONSUMER_VERSION: ${{ github.sha }}
          PACT_DIRECTORY: target/pacts
        working-directory: ./petstore-consumer
        run: mvn pact:publish

      - name: Run verify pacts
        working-directory: ./order-provider
        run: mvn clean test -Dpact.verifier.publishResults=true -Dpact.provider.version=${{ github.sha }}